### ISSUE TITLE
Invalid OCS content returned for app notes

### ISSUE THREAD

**Issue by tlindener** [owncloud/notes#101]
Hi,

I've installed notes on a clean 8.0.2 installation with MySQL. Since then I get the error message:
"Invalid OCS content returned for app notes" in my log file. Furthermore there is only an empty  Text window as described here.
https://github.com/owncloud/notes/issues/98

**Comment by Raydiation** [comment]
This is not a notes app issue. It's because the app is not on the store anymore and your ownCloud tries to find updates and finds none.
