### ISSUE TITLE
ownCloud 8: The API produces duplicate notes

### ISSUE THREAD

**Issue by phedlund** [owncloud/notes#107]
Steps to reproduce (this can be done with something like RESTClient):
1. Add a note with the Create API call.
2. Update the returned note with the Update API call.
3. Add another new note with the Create API call.

Now (and only after doing all three step) you will have three notes, two with a creation time stamp of step 1 and one with a creation time stamp of step 3.

I can reproduce this reliably using the iOS CloudNotes app (which has been a long-standing issue for me and several users) and independently of the app using RESTClient in Firefox.

**Comment by Raydiation** [comment]
Which version do you use?

**Comment by phedlund** [comment]
The latest officially released version of oC and 1.0 of Notes.

**Comment by Raydiation** [comment]
Can you check if it occurs in 8.1 and the latest release? This is most likely a core filesystem big

**Comment by Raydiation** [comment]
Bug*

**Comment by phedlund** [comment]
Unfortunately I don't have time to set up a test server right now and I don't want to mess with my regular server right now. Since I know you have been developing for 8.1 for some time it should be fairly easy to test with something like RESTClient.

**Comment by Raydiation** [comment]
@LukasReschke can you check?

**Comment by Raydiation** [comment]
Ok, can not reproduce on 8.1, will try on 8.0

**Comment by Raydiation** [comment]
Ok, tested 1.0.0 on ownCloud 8, can not reproduce

**Comment by Raydiation** [comment]
Did you use application/json as Content-Type header?

**Comment by phedlund** [comment]
> Did you use application/json as Content-Type header?

Yes.

**Comment by Raydiation** [comment]
I've tried it in the stable8 branch BTW. Maybe already fixed?
