### ISSUE TITLE
The URL you request datafrom dosen't seem to exist.

### ISSUE THREAD

**Issue by ctgcwiqc** [owncloud/notes#108]
Check you spelling or internet connection.
Just installed these apps, not working out of the box.  

OC 8.0.3
Ubuntu 14.04 server
Notes 1.0.0 installed and working in OC
MyOwnNotes 1.5 installed on Motox 2 android V4.4.4

**Comment by Raydiation** [comment]
Not a notes app issue but likely a setup issue or issue with MyOwnNotes

**Comment by freibadschwimmer** [comment]
Same issue.

OC 8.0.3, php 5.4, apache server on debian 7, certificate is added to key chain;
installed notes 1.0.0; can access it via webinterface, works fine in browser, but can't access from app (v1.5)

i copied the server address and username into the app settings, retyped passwd several times, so there shouldn't be spelling mistakes, yet i get the message, url not exists.
