### ISSUE TITLE
API does not work, 401 error

### ISSUE THREAD

**Issue by Dreamsorcerer** [owncloud/notes#109]
Trying to use the API just gives me a 401 error now. I can repeat this behavior in the browser, if I access the URL, it does not log me in with the passed username:password but just shows me the login screen.

This is v1.0 on OC 8.0.3.

**Comment by Raydiation** [comment]
401 means unauthorized, using the browser to access the api won't work because the browser tries to use cookies which is forbidden because of csrf issues. 

Can you try curl?

**Comment by Dreamsorcerer** [comment]
That's interesting, curl does work, but I get 401 in my GNOME shell extension. Guess this is a bug with GNOME then?

**Comment by Raydiation** [comment]
Yes, probably related to their web implementation

**Comment by Raydiation** [comment]
Basically you must not use cookies ;)
