### ISSUE TITLE
Use .md for files with markdown syntax

### ISSUE THREAD

**Issue by icewind1991** [owncloud/notes#110]
This makes it possible to remember the markdown checkbox on a per-file basis by using the mimetype the file is saved as and makes markdown notes work with other markdown app such as https://github.com/icewind1991/owncloud-markdown

cc @Raydiation

**Comment by Raydiation** [comment]
I've thought about this too, ideally we would only go for .md extensions which however are not being able to be viewed in a text editor on Windows by default. Is this a real problem?

About mixing both extensions:
* When should the file be renamed? Once you toggle markdown mode? Isn't that a bit overkill :D?
* What about apps that use the webdav interface to sync your notes? Those won't show files ending in .md

Personally I'm leaning towards postfixing all notes with .md

@LukasReschke @jancborchardt opinions?

**Comment by jancborchardt** [comment]
Can we change the mimetype of the file, but not touch the extension?

**Comment by icewind1991** [comment]
Yes but it will be set back to the default for the extension once the file is written to again

**Comment by AsavarTzeth** [comment]
For starters could we at least allow the app to use files with .md extension?

Then those of us that don't have any of the above mentioned issues could use it with our existing files without breaking things elsewhere.

Btw, is this the right issue, or should I have commented on https://github.com/owncloud/notes/issues/111

**Comment by jancborchardt** [comment]
Yeah, basically the main thing is that the app should be able to read markdown files. We don't have the checkbox anymore, but inline markdown, so the extension change is not really necessary anymore.

Cc @Henni

**Comment by jancborchardt** [comment]
Closing in favor of https://github.com/owncloud/notes/issues/111
