### ISSUE TITLE
External API not working

### ISSUE THREAD

**Issue by pierrejochem** [owncloud/notes#112]
Dear all,

I'm trying to access the external API from the notes app (Version 1.0), but can't get it to run:

I'm using the following URL:

https://[Server]/index.php/apps/notes/api/v2/notes

together with the Basic Auth Header. Is there any clou?

If I login to the cloud and call the url afterwards then I get a result. That is a little bit strange for me.

All other API's are working like a champ...

Cheers,

Pierre

**Comment by pierrejochem** [comment]
https://[username]:[password]@[Server]/index.php/apps/notes/api/v0.2/notes

**Comment by pierrejochem** [comment]
<pre>
{"message": "Current user is not logged in"}
</pre>

**Comment by LukasReschke** [comment]
Which version of core? What is the *exact* request you issued, etc?

**Comment by Raydiation** [comment]
Did you try 1.1.0 yet?

**Comment by pierrejochem** [comment]
No, just Version 1.0.0

Core Version 8.0.4

**Comment by pierrejochem** [comment]
Header:
<pre>
Authorization: Basic [Base64([Username]:[Password])]
</pre>

**Comment by pierrejochem** [comment]
1.1.0 is only working with core Version 8.1 and this version is not official releases yet :-(

**Comment by Raydiation** [comment]
@pierrejochem sure, but can you still try it so we can rule out that the issue is already fixed?

**Comment by pierrejochem** [comment]
I will try it tomorrow

**Comment by pierrejochem** [comment]
Same behaviour :-(

**Comment by pierrejochem** [comment]
Maybe one thing. If I call the other API's in the browser like:

https://[myserver]/owncloud/ocs/v1.php/cloud/user?format=json 

then I get a Basic auth login like it should be and get the data. 

With the notes app there is only a redirect to the login page what is wrong.

**Comment by Raydiation** [comment]
Can you try curl? This works for me and I can't reproduce your issues:

    curl https://server/index.php/apps/notes/api/v0.2/notes -u user:pass

**Comment by pierrejochem** [comment]
Arg, I found it. I had an old app installed with a wrong routing definition and curl gave me the error message. After I disabled it I got it. Sorry for consuming your time.

Thank you very much
