### ISSUE TITLE
Display markdown inline instead of 2-up

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/notes#115]
Instead of the indirect two-pane display of markdown, we should display it inline. That is, a line which starts with a hash (#) is automatically formatted as h1, while the hash also stays there. Same for the other things.

This is similar to how the quite popular [iA Writer](https://ia.net/writer/) and [Markdownify](https://tibastral.github.io/markdownify/) (based on CodeMirror, with jQuery) do it.

What do you think @LukasReschke @Raydiation @owncloud/designers?

**Comment by MorrisJobke** [comment]
:+1:

**Comment by pierrejochem** [comment]
:+1:

**Comment by Henni** [comment]
:+1:

**Comment by jancborchardt** [comment]
I see 3 volunteers raising their hands. :)

**Comment by Henni** [comment]
Challenge accepted! #118

**Comment by Henni** [comment]
Should the inline markdown editor replace the normal txt editor?
This way we wouldn't need a switch like this:
![image](https://cloud.githubusercontent.com/assets/1267827/8600013/df2ed114-2663-11e5-8bdc-0b867150a16e.png)

**Comment by jancborchardt** [comment]
@Henni I would say yes. Because if it’s inline, then you can simply edit text documents – but when you use Markdown it gets awesome automatically.

**Comment by Henni** [comment]
Fixed by #118

**Comment by jancborchardt** [comment]
:smiley_cat:
