### ISSUE TITLE
Not able to reactivate app after upgrade to owncloud 8.1

### ISSUE THREAD

**Issue by Henni** [owncloud/notes#116]
After upgrading to owncloud 8.1 and reenabling the app I am not able to use it anymore.

The app path shows me the following page:
![image](https://cloud.githubusercontent.com/assets/1267827/8573219/cd7ab1be-2590-11e5-8dd9-c29364e492c0.png)

With the error:
```
Module with id: OC_DEFAULT_MODULE does not exist.
Module with id: OC_DEFAULT_MODULE does not exist. Please enable it in your apps settings or contact your administrator.
```

Maybe this isn't an error caused by the app but by owncloud/core. I have no idea what the error means.

**Comment by Raydiation** [comment]
It's from the encryption app, ./lib/private/encryption/manager.php:				$hint = $this->l->t('Module with id: %s does not exist. Please enable it in your apps settings or contact your administrator.', [$moduleId]);

**Comment by Henni** [comment]
@Raydiation thanks!
But why did this only happen with the notes app?
And could we give this error message a bit more context?

**Comment by Raydiation** [comment]
@Henni honestly no idea. Wrong issue tracker to discuss this since this is a core issue.
