### ISSUE TITLE
Inline markdown editing: View jumps when editing a note which is larger than a page

### ISSUE THREAD

**Issue by BernhardPosselt** [owncloud/notes#127]
@Henni @jancborchardt 

How to reproduce:
* Paste the news app's markdown into the editor
* Choose a location at the the in the lower quarter to start editing
* After typing the first character, the view scrolls up and you can't see what you're actually editing.

Running newest master and firefox stable

**Comment by Henni** [comment]
I can reproduce this in Firefox. Chrome works as expected.
I'll try to find out why this happens.
