### ISSUE TITLE
503 (Service unavailable)

### ISSUE THREAD

**Issue by Henni** [owncloud/notes#131]
### Steps to reproduce
1. Open app
2. Click 'new note'

### Expected behaviour
The app should list all existing notes and create a new note

### Actual behaviour
The app responds with an error instead of listing the notes:
`Failed to load resource: the server responded with a status of 503 (Service Unavailable)`
The app responds with an error instead of creating a note, but creates the file:
`POST https://---/index.php/apps/notes/notes 503 (Service Unavailable)`

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
```
$ php --version
PHP 5.5.9-1ubuntu4.11 (cli) (built: Jul  2 2015 15:23:08) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with the ionCube PHP Loader v4.6.0, Copyright (c) 2002-2014, by ionCube Ltd., and
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
````

**ownCloud version:** (see ownCloud admin page)
8.1.0.8 (stable)

**Updated from an older ownCloud or fresh install:**
updated from owncloud 7.0

**List of activated apps:**
Enabled:
 - activity: 2.0.1
 - bookmarks: 0.4
 - calendar: 0.7.1
 - contacts: 0.4.0.0
 - encryption: 1.0.0
 - external: 1.2
 - files: 1.1.9
 - files_external: 0.2.3
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - news: 5.3.8
 - notes: 1.1.0
 - provisioning_api: 0.2
 - tasks: 0.7.0
 - templateeditor: 0.1

Disabled:
 - documents
 - files_trashbin
 - mail
 - user_external
 - user_ldap
 - user_webdavauth

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'oco027lf2q1n',
  'passwordsalt' => '---',
  'secret' => '---',
  'trusted_domains' => 
  array (
    0 => '---',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => '---/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => '---',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '---',
  'dbpassword' => '---',
  'installed' => true,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'theme' => '',
  'maintenance' => false,
  'mail_smtpmode' => 'php',
  'mail_smtpauth' => 1,
  'mail_smtphost' => '---,
  'mail_from_address' => 'owncloud',
  'mail_smtpname' => '---',
  'mail_smtppassword' => '---',
  'mail_domain' => '---',
  'mail_smtpport' => '25',
  'mail_smtpauthtype' => 'LOGIN',
  'loglevel' => 1,
  'singleuser' => false,
);

**Are you using external storage, if yes which one:**
Dropbox

**Are you using encryption:**
yes

**Are you using an external user-backend, if yes which one:**
no

### Client configuration
**Browser:**
Chrome 45 (beta)

**Operating system:**
Ubuntu 14.04

#### Web server error log
[empty]

#### ownCloud log (data/owncloud.log)
[empty]

#### Browser log
```
GET https://---/index.php/apps/notes/notes 503 (Service Unavailable)
or
Failed to load resource: the server responded with a status of 503 (Service Unavailable)

POST https://---/index.php/apps/notes/notes 503 (Service Unavailable)
```

**Comment by Raydiation** [comment]
Can you pull from master?

**Comment by Henni** [comment]
Yes I just pulled your gulp changes, but this doesn't change anything.

This error only occurs on my server and not on my development environment. Maybe because I use the encryption app!?

**Comment by Raydiation** [comment]
Can you deactivate it? I don't think the app is compatible, there are multiple weird bugs in core, also regarding the news app. Best solution is IMHO to wait for fixes in core and not handling it at all.

**Comment by Raydiation** [comment]
Given that the encryption app does not add anything useful for the average owncloud user

**Comment by Raydiation** [comment]
Ah right encryption update is broken, wait for 8.1.1

**Comment by Henni** [comment]
Ok thanks
