### ISSUE TITLE
Existing notes not found by notes app

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/notes#133]
With latest master, the existing notes are not found by the Notes app anymore. This was probably introduced recently, some time after the inline Markdown implementation.

This is the JS log:
```
angular.js?v=45360383019c34fc1b722568d8ed4110:10316 GET http://localhorst/owncloud/index.php/apps/notes/notes 503 (Service Unavailable)(anonymous function) @ angular.js?v=45360383019c34fc1b722568d8ed4110:10316sendReq @ angular.js?
v=45360383019c34fc1b722568d8ed4110:10135$get.serverRequest @ angular.js?
v=45360383019c34fc1b722568d8ed4110:9847processQueue @ angular.js?
v=45360383019c34fc1b722568d8ed4110:14347(anonymous function) @ angular.js?
v=45360383019c34fc1b722568d8ed4110:14363$get.Scope.$eval @ angular.js?
v=45360383019c34fc1b722568d8ed4110:15574$get.Scope.$digest @ angular.js?
v=45360383019c34fc1b722568d8ed4110:15385$get.Scope.$apply @ angular.js?
v=45360383019c34fc1b722568d8ed4110:15679bootstrapApply @ angular.js?
v=45360383019c34fc1b722568d8ed4110:1582invoke @ angular.js?
v=45360383019c34fc1b722568d8ed4110:4379doBootstrap @ angular.js?
v=45360383019c34fc1b722568d8ed4110:1580bootstrap @ angular.js?
v=45360383019c34fc1b722568d8ed4110:1600angularInit @ angular.js?
v=45360383019c34fc1b722568d8ed4110:1494(anonymous function) @ angular.js?
v=45360383019c34fc1b722568d8ed4110:27867x.Callbacks.c @ jquery.min.js?
v=45360383019c34fc1b722568d8ed4110:4x.Callbacks.p.fireWith @ jquery.min.js?
v=45360383019c34fc1b722568d8ed4110:4x.extend.ready @ jquery.min.js?
v=45360383019c34fc1b722568d8ed4110:4q @ jquery.min.js?
v=45360383019c34fc1b722568d8ed4110:4
```

@Raydiation @LukasReschke @Henni do you have the same issue?

**Comment by Henni** [comment]
`http://localhorst/owncloud/index.php/apps/notes/notes 503 (Service Unavailable)` looks similar to the error in #120.
I don't have this issue.

**Comment by jancborchardt** [comment]
Hm … weird. How can I most cleanly reset everything? Already tried disabling and enabling.

**Comment by jancborchardt** [comment]
Maybe it’s a special character in a filename (like a [), or a different filetype in the folder (like pdf) halting the discovery process?

**Comment by Henni** [comment]
I added files with special characters and different file extensions to the folder and it still worked for me.

The only place I can think of is the database. But I have no idea which setting could break your setup this way.

**Comment by Raydiation** [comment]
Can not reproduce btw

**Comment by Raydiation** [comment]
@Henni nothing is stored in the db, so I'd exclude that vector

**Comment by Raydiation** [comment]
@jancborchardt are you running encryption?

**Comment by jancborchardt** [comment]
@Raydiation I used to, but not anymore. There are sometimes old errors on that so maybe I should just wipe my dev environment.

If you both can not reproduce I assume it's an issue with my setup.
