### ISSUE TITLE
Save State Indicator

### ISSUE THREAD

**Issue by stefan-niedermann** [owncloud/notes#134]
The Notes App saves automatically, but many people complained, that there is no visiual feedback, if the note is already saved (maybe there is a big latence on mobile or so).

What do you think about a circular loading icon in the sidenav next to the garbage icon when the app is currently saving? or a dot indicator (. -> .. -> ... -> . -> .. -> ... -> . -> .. -> ...) ?

@jancborchardt

**Comment by jancborchardt** [comment]
The thing is that it would pop up all the time, since a note is saved all the time. It would always show a spinner and then a checkmark again when you type.

**Comment by stefan-niedermann** [comment]
i agree, a circular loading indicator would really be heavy. i thought on something like this:
 http://ak-hdl.buzzfed.com/static/2013-10/enhanced/webdr02/8/12/anigif_enhanced-buzz-1352-1381250034-0_preview.gif

**Comment by jancborchardt** [comment]
We don’t use that anywhere though, and it’s really not a lot different in working. It pops up and goes away again. :\

**Comment by Raydiation** [comment]
Closing this, there is a saving indicator (spinning wheel) but it's likely that it's saving so fast, that you won't see it ;)
