### ISSUE TITLE
App management in ownCloud 8.1.1 is not showing latest app version

### ISSUE THREAD

**Issue by rakekniven** [owncloud/notes#135]
On my ownCloud v8.1.1 I have notes app installed in version 1.0.0
Got this version kept from previous 8.0.x versions.
Today I saw notes app in version 1.1.0 on github. 
On app store there is only an outdated version 0.5.5

Please adapt release information to show latest version in ownCloud's app administration.

**Comment by tapir** [comment]
I don't see it on app store at all

**Comment by BernhardPosselt** [comment]
DUP #73
