### ISSUE TITLE
Left-align headings and lists

### ISSUE THREAD

**Issue by Henni** [owncloud/notes#136]
The idea is to left align elements like headings and lists with the remaining text.
![image](https://cloud.githubusercontent.com/assets/1267827/9831006/d94daff8-5945-11e5-87f4-07f52db0fc28.png)

cc @jancborchardt

EDIT:
We should probably only do this on desktop as we loose some space on the left.

**Comment by jancborchardt** [comment]
Yup! Good call. The list entries should also be lined up properly to the left, see https://en.wikipedia.org/wiki/Hanging_punctuation
