### ISSUE TITLE
Lighthttpd Support

### ISSUE THREAD

**Issue by wompydomp** [owncloud/notes#144]
Hi,
Thanks for working on this project. I tried to sync with myownnotes 1.6 downloaded through fdroid and I get a "Not getting correct JSON from Server." error. I checked the requirements and as far as I can tell lighttpd is not a supported webserver and I assume this is the reason I don't get a connection.

Are there any plans to support lighttpd in the future?
I am running  Owncloud 8.1.3 on Arch linux.

**Comment by Henni** [comment]
I haven't worked with lighthttpd but I believe this is a core issue.
Did you follow this configuration guide? https://doc.owncloud.org/server/7.0/admin_manual/installation/lighttpd_configuration.html

**Comment by rakekniven** [comment]
notes is just an app running inside ownCloud framework.
Please file an issue there. 
Issue should be closed IMHO
