### ISSUE TITLE
Support plain text mode

### ISSUE THREAD

**Issue by zbraniecki** [owncloud/notes#155]
My OwnCloud provider (OwnCube) just enabled Notes app, which is sweet. I'm trying to replace my current solution - simplenote - with it.

The only thing that I miss is ability to define my notes as plaintext, store them as `.txt` files. Currently, the notes are saved as `.htm` which means that editing them on local desktop is not very convenient and since I don't use markup, I'd prefer to be able to keep them as `.txt`.

**Comment by Henni** [comment]
Your provider probably enabled the [ownNotes App](https://github.com/Fmstrat/ownnote) which uses html files.
This notes app uses `.txt` files for notes.

Please open an issue over there.
