### ISSUE TITLE
FavIcon when using notes

### ISSUE THREAD

**Issue by improti** [owncloud/notes#159]
I'm using the web-interface in a so-called pinned tab in FireFox, i.e. the tab only shows the fav-icon and no text or title. For OwnCloud this is mostly the OwnCloud favicon, though the tasks app switches to a different icon. I now installed and activated notes and realized that while I'm in the notes, the fav-icon is displayed empty. This makes it harder to find the OwnCloud tab again and doesn't look nice in general. Is this intended? Or a bug? Or only happening to me?

If in doubt my suggestion would be to just use the OwnCloud icon. Could imagine though that some people want to have a tab for notes at the same time with a tab for tasks, in which case using different icons per app would make sense. I don't know where to look for it, but somewhere in the repositories of the other apps should be appropriate code?

P.S.: Sorry for not filling the whole issue template on this, but it feels this is not needed here. If you guys need more information from me, please let me know and I'll get it for you.

**Comment by Henni** [comment]
I can reproduce this in Firefox. It doesn't happen in Chrome. I'll look into it.

A special icon for notes would be great. This is maybe a task for @jancborchardt

**Comment by Henni** [comment]
Looks like a very strange bug.
Opening the app via a link doesn't display the favicon while a refresh (`Ctrl+R`) of the notes app displays the icon properly.
@improti do you see the same behavior?

**Comment by improti** [comment]
Yes indeed. Each time I go into notes the icon is empty. Clicking on different notes and editing notes doesn't change that. After a reload the owncloud icon is displayed until I leave the notes app and come back again, which makes the icon disappear again. Guess clicking in the app is done by AJAX calls or something and doesn't effect the current state of the page in the opposite to reloading?

**Comment by Henni** [comment]
Maybe @BernhardPosselt has an idea?

**Comment by Henni** [comment]
Two approaches for custom favicons:
![favicon-blue](https://cloud.githubusercontent.com/assets/1267827/10268649/54f3e962-6abf-11e5-99f1-9c7c8490fc9c.png)
![favicon-white](https://cloud.githubusercontent.com/assets/1267827/10268650/54f5690e-6abf-11e5-9ad7-00cf827dd728.png)

**Comment by stefan-niedermann** [comment]
second one as it matches the app icon in the app menu.

**Comment by Henni** [comment]
#160 adds a custom favicon, but this doesn't fix the problem in Firefox.
The Firefox issue has to do with some javascript code. Disabling `app.min.js` fixes the problem but obviously breaks the app.
