### ISSUE TITLE
Extend API: Excerpt

### ISSUE THREAD

**Issue by stefan-niedermann** [owncloud/notes#163]
Every Note should have a server-generated excerpt (like title) with 15 - 20 words.
This way every client could show a small snippet.
See https://github.com/stefan-niedermann/OwnCloud-Notes/issues/6 for further information.

cc: @jancborchardt

**Comment by Henni** [comment]
Currently the API sends only whole notes.
So there is no gain in adding an excerpt as you always receive the complete content.
This way you are able to adjust the excerpt to your use case by shortening the content to a length that fits for you.

**Comment by stefan-niedermann** [comment]
Yeah, the idea was, that different clients could display the same excerpt of the same note.

Would be 3 lines of code for me on client side, but maybe it makes sense, we do it on server?

**Comment by Henni** [comment]
Different Clients may want different excerpt lengths. A desktop client probably wants a longer preview than a mobile client. And even mobile clients may choose different lengths. For example if you want to display a preview in a single line it depends on the font size of your app how long the except should be.

**Comment by stefan-niedermann** [comment]
persuaded
