### ISSUE TITLE
Strip Markdown on Title

### ISSUE THREAD

**Issue by stefan-niedermann** [owncloud/notes#164]
In my Client i strip all Markdown from the title because often the first line contains a header, like `#ToDo`.

Current Situation:

![screenshot](https://cloud.githubusercontent.com/assets/4741199/10303905/0b12592e-6c17-11e5-94a7-48945a9ca894.png)

Expected Behaviour:

Display only "ToDo"

**Comment by Henni** [comment]
This should already work:
![image](https://cloud.githubusercontent.com/assets/1267827/10304655/cab39064-6c1b-11e5-93be-56a3aa3aa1f4.png)
Are you seeing this on the current master?

**Comment by stefan-niedermann** [comment]
Ah, when did you implement this? I'm using Notes 1.0.0 with OC 8.1.1 ;)

**Comment by stefan-niedermann** [comment]
Why can't i see the update for Notes 1.1.0 in ownCloud?

![screenshot](https://cloud.githubusercontent.com/assets/4741199/10305208/4587d928-6c1f-11e5-8cc0-dbbb29739524.png)

Release Notes says, OC 8.1 is enough?

**Comment by Henni** [comment]
The app isn't released to the app store yet.
You have to update it like you installed it, via github.
Either download the current version or run a `git pull`.
