### ISSUE TITLE
Owncloud 8.2 compatibility

### ISSUE THREAD

**Issue by hubgitti** [owncloud/notes#170]
The current Notes version (1.1.0) is not compatible to the new owncloud version 8.2.

**Comment by Henni** [comment]
You are probably talking about ownNote which you can find over here:
https://github.com/Fmstrat/ownnote

This app isn't released to the app store yet and does support owncloud 8.2.

**Comment by Henni** [comment]
@hubgitti reread your description....
I'll release version 2.0 next week. Please use the master branch in the meanwhile.

**Comment by hubgitti** [comment]
Thanks!
