### ISSUE TITLE
Deleting the current "top" note leads to crash

### ISSUE THREAD

**Issue by irgendwie** [owncloud/notes#172]
If you delete the current "top" note, the notes app crashes because of an NotFoundException!
(Deleted it via command line)

>Remote Address: 127.0.0.1
Request ID: d1vYIEAjozg3xavvvK+M
Type: OCP\Files\NotFoundException
Code: 0
Message: /admin/files/Notes/New note (2).txt
File: /srv/http/oc/lib/private/files/node/root.php
Line: 181

**Comment by Henni** [comment]
@irgendwie Does this bug still occur and if so how exactly do I reproduce it?

**Comment by irgendwie** [comment]
Totally forgot this issue... It's more a owncloud core "bug" - files deleted via command line are not recognized by core/files and must be reindexed, therefore no notes bug.
