### ISSUE TITLE
Info pls.

### ISSUE THREAD

**Issue by witzker** [owncloud/notes#180]
I have read that this app shown on
https://apps.owncloud.com/content/show.php?action=content&content=155599

Is develloped here now

I downloaded the code here but it looks quit different as shown in the sceenshot of the link above and the hompage of (former? ) developper
http://www.ruinelli.ch
https://www.ruinelli.ch/wordpress/wp-content/uploads/2012/12/Screenshot01.png

Pls explain what is going on.

Regards Witzker

**Comment by Henni** [comment]
The notes app you are referring to is back from owncloud version 4.5, while the current release is 8.2.
This notes app is a different app and still maintained as opposed to https://apps.owncloud.com/content/show.php?action=content&content=155599
