### ISSUE TITLE
Notes can not be installed on ownCloud 8.2.1

### ISSUE THREAD

**Issue by rakekniven** [owncloud/notes#184]
Just updated my ownCloud from 8.1.4 to 8.2.1 and apps module tells me:

![bildschirmfoto 2015-12-12 um 16 12 12](https://cloud.githubusercontent.com/assets/2069590/11762590/7cf3fff8-a0eb-11e5-8153-2da1b6524e0f.png)

**Comment by rakekniven** [comment]
Can somebody make it available for 8.2.x please?

**Comment by jancborchardt** [comment]
This was fixed some time ago, as you can see from the max-version in https://github.com/owncloud/notes/blob/master/appinfo/info.xml#L13
Are you sure you have the latest Notes package installed as well?

@Henni @LukasReschke this was published, right?

**Comment by jonas2515** [comment]
Looks like the change isn't included in the latest github release (version 1.1.0 from May).
Maybe you should update the releases, some people here use because they want a stable version.

**Comment by Henni** [comment]
I just released v2.0: https://github.com/owncloud/notes/releases/tag/v2.0 which contains all recent changes (including the update for 8.2 and 9.0).

**Comment by rakekniven** [comment]
Did a manuel update, automatic update did not work. It does not show up in app center.
 Works fine. Thanks.

**Comment by Henni** [comment]
@rakekniven I'm currently trying to fix this in https://github.com/owncloud/notes/issues/185
