### ISSUE TITLE
Notes doesn't read files created outside of Notes API

### ISSUE THREAD

**Issue by jsit** [owncloud/notes#186]
I use nvALT with my /Notes directory to create notes files on the desktop, but notes created this way aren't visible to the Notes web app, I assume because there's never an event that adds them to the database. Would there be a way to make this possible?

**Comment by irgendwie** [comment]
It's the same as #172 

The Notes app uses the files API of ownCloud and this behavior is **expected** (https://github.com/owncloud/core/issues/21122)

**Comment by jsit** [comment]
Thanks @irgendwie.

> files deleted via command line are not recognized by core/files and must be reindexed

Is it possible to manually reindex files in the /Notes directory so that they appear in the Notes webapp? I've tried `files:scan` with no success.

**Comment by irgendwie** [comment]
The command should work, as it rescans the filesystem... Was there an error or what happened?
https://github.com/owncloud/core/issues/21122#issuecomment-163691718

**Comment by jsit** [comment]
Rescan appears to be successful, but files in `/Notes/` still don't appear
in Notes webapp.

**Comment by irgendwie** [comment]
Maybe nvALT produces files with "fancy" file extensions, only the ones mentioned in #161 are recognized by the notes app, could this be the problem?

**Comment by jsit** [comment]
No, all these files have the .txt extension.

Have you tried and succeeded to "load" new .txt files into the Notes webapp using files:scan?

**Comment by irgendwie** [comment]
Creating files in the Notes directory leads to no files visible in the notes app for me, but after a "occ files:scan" everything is visible, as expected. So in general it should work, as I tested it.

Are the files at least visible in the files app, after the "occ files:scan" call?

**Comment by jsit** [comment]
Yes, they are visible in the files app. I'm on ownCloud 8.1.3 and notes 2.0.0.

**Comment by irgendwie** [comment]
Sorry, then I'm out of ideas...
Something interesting in the log files?

@Henni ideas?

**Comment by jsit** [comment]
I think I may have identified the issue. I cleared all my files out of the Notes directory and started moving them back in a little at a time. I discovered that after adding files whose filenames start with `#`, Notes didn't recognize them and would no longer recognize new files added after those (I assume because `#` is first alphabetically?).

**Comment by Henni** [comment]
`#`s in filenames are treated specially because they are used for headers in markdown.

Could you please take a look at the log file (data/owncloud.log) and search for any errors regarding the notes app?

**Comment by jsit** [comment]
I don't see any messages in the log when I do the occ scan.

**Comment by jsit** [comment]
Looking more closely at this, I think the issue may be in files with "invalid" characters in them.

**Comment by jsit** [comment]
I think the issue is that somehow two text files with iso-8859-1 encoding ended up in my Notes folder. Once I got those out of there, everything worked fine. Thanks!
