### ISSUE TITLE
No way to change note's name

### ISSUE THREAD

**Issue by Olhur** [owncloud/notes#191]
Hello!
I've been using OwnCloud for some time, but lately I have decided to switch from Evernote to ownCloud's Notes. Although it serves its purpose, I think I have encountered a bug or lack of functionality, which is note renaming / or even naming.

All of my notes are named "New note", and even when I change their names in Files, they keep their New Note name. Initially, when entering the page, the name of the file is displayed correctly, but after activating the note, it switches back to New note once again.

Is it truly a bug or am I missing something?

Best regards!
Filip

**Comment by Henni** [comment]
A notes name is determined based on the first line of it. If this doesn't work it might be a bug, otherwise it is intended behaviour.

@Olhur Does the note's name change to the first line of the content when you edit the note?

**Comment by Olhur** [comment]
@Henni You are right, this is working as you said! The issue is, when I create a new note, after hitting first key a new line appears and the first line is empty (this looks like an expected behaviour, but was misleading). I have found that when inspecting notes in Files text editor, where line numbers are shown.

Thank you for help!

**Comment by Henni** [comment]
The newline actually is a bug (#168) i couldn't reproduce yet. I'll take another look.
