### ISSUE TITLE
Split title from content

### ISSUE THREAD

**Issue by stefan-niedermann** [owncloud/notes#198]
I would like to suggest to split the title from content for a better separation.
Benefits:
- User know insantly what the later note name will be
- No complicated generate-title-algorithm
- Less problems with different sync-clients

Please: Get some inspiration about Atlassian Confluence ("Page Title" and below):

<img width="820" alt="editor and page data" src="https://cloud.githubusercontent.com/assets/4741199/12922333/451c20bc-cf51-11e5-9c22-5897b8128c21.png">

It looks like a single editing page, not like a separate input field. But it is styled with bigger font size and can not be removed. Technically it's an `input type="text"` and the following `textarea`

**Comment by Henni** [comment]
I believe we should keep it as is. OneNote by Microsoft does it similar to our approach and tries to handle the first line of the content as the title. This way you can start taking notes without even knowing what the title should be.
Notes might not be as structured as wiki entries (Confluence) or other documents.

@owncloud/designers what do you think?

**Comment by jancborchardt** [comment]
Yeah, @Henni same way as it’s done in Google Keep. We should keep it simple.

Atlassian Confluence is a mainly enterprise app, with lots of other features too (formatting etc), we shouldn’t compare to them.

**Comment by stefan-niedermann** [comment]
> Atlassian Confluence is a mainly enterprise app, with lots of other features too (formatting etc), we shouldn’t compare to them.

Well, i didn't suggest to compare with Atlassian Confluence Features, but to how they solved it to make title/content separation as simple as possible.

**Comment by jancborchardt** [comment]
Yeah, but the beauty of the Notes app is its simplicity. You don’t need to think of a title because most of the time notes don’t really have a title. Documents have titles, and this is not what this is for. It creates a mental barrier, if ever so slightly.
