### ISSUE TITLE
encrypt notes

### ISSUE THREAD

**Issue by lowtower** [owncloud/notes#200]
It would be nice to have the possibility to encrypt notes. 
Especially for using owncloud notes in mobile devices it would be very useful.

**Comment by Henni** [comment]
Notes are stored on the server as files, which can be encrypted.
See https://owncloud.org/blog/encryption-2-0-in-owncloud-server-8-1/

**Comment by lowtower** [comment]
Yes, of course!
But using mobile apps such as "ownCloud Notes" or "MyOwnNotes" - how are the notes handled on the mobile devices?
In Issue [83 on "ownCloud Notes"](https://github.com/stefan-niedermann/OwnCloud-Notes/issues/83) Stefan mentions a missing server side API!
Cheers,
LT.

**Comment by pbek** [comment]
As a side note to #201: [QOwnNotes](http://www.qownnotes.org) now uses AES-256 encryption.
