### ISSUE TITLE
Feature Request: encrypt and decrypt note

### ISSUE THREAD

**Issue by dasmaetthes** [owncloud/notes#201]
Would be nice to have the possibility to encrypt and decrypt a note like you can do in [QOwnNotes ](http://www.qownnotes.org)and having the possibility to share/sync the key over different devices.

**Comment by Henni** [comment]
duplicate of https://github.com/owncloud/notes/issues/200, please continue discussion over there

**Comment by pbek** [comment]
As a side note: [QOwnNotes](http://www.qownnotes.org) now uses AES-256 encryption.
