### ISSUE TITLE
Can't create new notes from the browser

### ISSUE THREAD

**Issue by ppmt** [owncloud/notes#205]
Hello
I have installed the latest app (2.0.0)

When I click on "New note" nothing happens. I can't write anything in the panel on the right. When I open the firefox console I can see the following message ( I hid my domain)

`POST XHR https://mydomain/index.php/apps/notes/notes [HTTP/2.0 403 Forbidden 245ms]`

I assume it must be something misconfigured somewhere but can't find what it is. 

Also what is strange is that if I create a note from my tablet using the MyOwnNotes app then it gets uploaded to my ownCloud and then I can update these notes from the browser.

**Comment by ppmt** [comment]
Something I found while I am trying to debug it

13:15:10.520 Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src https://mydomain 'unsafe-eval'").1 notes

**Comment by Henni** [comment]
That might actually be related. I'm currently working on the contacts app and don't have time to look into this.
If you find a fix a PR would be really welcome! Otherwise I will hopefully look into this soon..

**Comment by ppmt** [comment]
I am not sure I will find a fix but will keep looking. My understanding of protocol is not that good I am afraid.
thanks for the help.

euh... what does PR stands for? :(

**Comment by Henni** [comment]
@ppmt Pull Request ;)

**Comment by ppmt** [comment]
Continuing my troubleshooting.

On the debugging output of the 403 there is another info that I missed previously missed. In the page source code I can see this (it doesn't appear in the browser though!)

<div id="nojavascript"> <div> This application requires JavaScript for correct operation. Please <a href="http://enable-javascript.com/" target="_blank" rel="noreferrer">enable JavaScript</a> and reload the page. </div> </div>
ownCloud

    Access forbidden

ownCloud – web services under your control

But Javascript is enabled (I have checked) 

Regarding the CSP error. Looking through the code of the app I found in the file  js/vendor/angular/angular.js some reference to CSP (Starting line 23293). It mentions among other that the error I reported can occur that it is apparently more an annoyance that anything (see line 23311)

**Comment by ppmt** [comment]
Sorry me again. I hope this is not considered spamming.

I have managed to get it to work. My owncloud instance is on a shared host and via the Cpanel I deactivated the mod_security for my domain.

I can now create a new note from the browser. Obviously it is not a final solution

**Comment by Henni** [comment]
This is definitely not spamming. Every information is helpful.
Maybe @LukasReschke can take a look.

**Comment by ppmt** [comment]
I think somehow the mod_security option is causing the main issue.
I realise that something it's causing some issue with Tasks as well. With mod_security on the new task are not registering. Without it works fine.

Need to read more on what mod_security is about...

**Comment by Paviluf** [comment]
I have the same problem. Here is the error I get :
```
angular.js?v=537aea9d83c3e3f25038ab01127ddbbe:10722

POST https://xxx.com/index.php/apps/notes/notes 403 (Forbidden)
(anonymous function) @ angular.js?v=537aea9d83c3e3f25038ab01127ddbbe:10722
sendReq @ angular.js?v=537aea9d83c3e3f25038ab01127ddbbe:10515
serverRequest @ angular.js?v=537aea9d83c3e3f25038ab01127ddbbe:10222
processQueue @ angular.js?v=537aea9d83c3e3f25038ab01127ddbbe:14745
(anonymous function) @ angular.js?v=537aea9d83c3e3f25038ab01127ddbbe:14761
Scope.$eval @ angular.js?v=537aea9d83c3e3f25038ab01127ddbbe:15989
Scope.$digest @ angular.js?v=537aea9d83c3e3f25038ab01127ddbbe:15800
Scope.$apply @ angular.js?v=537aea9d83c3e3f25038ab01127ddbbe:16097
(anonymous function) @ angular.js?v=537aea9d83c3e3f25038ab01127ddbbe:23554
x.event.dispatch @ jquery.min.js?v=537aea9d83c3e3f25038ab01127ddbbe:5
v.handle @ jquery.min.js?v=537aea9d83c3e3f25038ab01127ddbbe:5
```

**Comment by gnzsnz** [comment]
Same issue for me. I don't have mod_security enabled. using 8.1.6 (stable) from owncloud ubuntu 14.04 repository

**Comment by susca** [comment]
Same issue with OC 9.0.0 and 9.0.1beta. Hosted on a debian server running apache2. What do you mean by mod_security?

**Comment by Paviluf** [comment]
It's working now for me. I think it's because I have disabled mod_security.

**Comment by susca** [comment]
Hello, is mod_security a apache module?

**Comment by Paviluf** [comment]
@susca https://en.wikipedia.org/wiki/ModSecurity

**Comment by susca** [comment]
@Paviluf  thank you. mod_security is not installed on my system but I have the problem anyway. So I gues mod_security is not (the only) problem. Which information can I provide to debug this?

**Comment by tobiasKaminsky** [comment]
Same for me:
OC 8.2.1 with notes 2.0.1, mod_security not enabled.
Using QownNote is working fine, so it is "just" a problem with this app.

**Comment by mikelupe** [comment]
Same for me:
OC 9, Notes 2.0.1, PHP 5.5.33-1, apache. My existing .txt files in the user's directory are not shown, neither can I add a new note.

**Comment by Lepelaar** [comment]
Hi OwnCloudies,

I have same issues as mentioned above, but - and I may be completely off track here - I think the problem is somewhere with the config.

I have owncloud installed on a hosted virtual server (installed via softaculous). This installation has a owncloud folder in the web/http part of the hosting, and a separate clouddata folder, higher up. 
To add Notes (2.0.1) I have DL'ed and unpacked the zip and ftp-ed it to the apps folder of the public owncloud folder. Then activated notes as admin of owncloud.

Now:
- I have a menu item "notes" that brings me to the notes page (index.php/apps/notes/#/) but if i click "new note" the browser reports an error (something about "<server>/apps/notes/notes" missing)
- I also have a new folder "notes" in my files page
- if I use the "MyOwnNotes" android app I can connect (which did NOT work before I installed Notes) and it lets me add notes to the notes-folder in files
- Also QOwnNotes (windows version) connects and reads/writes to the notes-folder in files (as to be expected)

My conclusion:
The API of the Notes app is working fine, but the config is trying to store new data in the wrong place (/notes/notes/ in the app folder instead of the clouddata (and user) folder) Therefore the notes-page can't read nor write notes and stays empty, while the notes folder (in files) is working fine.

But as said: I may be completely off ;-)
Still I hope someone knows how to fix it!

Cheers,
Lepelaar

**Comment by DatGizmo** [comment]
Same for me:
OC 8.2.2, Notes 2.0.1, nginx. My existing .txt files in the user's directory are not shown, neither can I add a new note.
The android app is just working fine.

**Comment by mikelupe** [comment]
Unfortunately when trying to get back the older version of notes 0.9 I get "Error: this app cannot be enabled because it makes the server unstable". 

I don't expect getting an updated 2.0.2 version soon, but where can I download a pre-2.0.1 version working with OC9.0 please? Thanks

**Comment by mikelupe** [comment]
Thanks for the notice Henni

**Comment by Henni** [comment]
#211 breaks the app if there is an index.php in the url, I think.
@LukasReschke @BernhardPosselt could you take a look please.
I believe linkTo isn't the correct function here. But I honestly don't what else to use. It almost looks like there isn't a core function for this use case.

**Comment by gnzsnz** [comment]
solved for me after upgrading to 9.0.0-3.1 (from 8.1.6) in ubuntu 14.04.

**Comment by BernhardPosselt** [comment]
OC.generateUrl('/apps/contacts')?

**Comment by Henni** [comment]
I'll test it.

**Comment by Henni** [comment]
Please take a look at #217 and test if it fixes your issues.

**Comment by tes5884** [comment]
@Henni that solved it for me...

Thanks!

**Comment by mikelupe** [comment]
Fix helped - thanks!

**Comment by Henni** [comment]
I **think** everyone in here who reported an issue without having `mod_security` installed should be fine with the fix in #217 
Everyone else including @ppmt seems to have a different issue which I can't reproduce yet.

**Comment by Henni** [comment]
I experimented with mod_security but still can't reproduce this.
Summoning our security master @LukasReschke

**Comment by predus2** [comment]
Hi I use android app correctly, show/delete/create notes, but in browser can´t show existing or create new notes, page is simply blank like there any notes. In dir /Notes are *.txt files with notes and correctly created/deleted/changed by android apps, corectly snyc by sync client to pc.

I tried Fix REST base url #217 (var baseUrl = OC.generateUrl('/apps/notes');), but no chage ...
I have installed mod_security, but When turn it off, nothing happend

**Comment by ppmt** [comment]
@Henni would it help if I gave you access to owncloud? I could create an admin account for you on it. it is hosted so cli access I am afraid. Let me know and I can arrange it. or if you want me to update some patch....

**Comment by Henni** [comment]
@ppmt That would be great to see the issue in action.

**Comment by ppmt** [comment]
Ok! I recently resinstalled Owncloud and now I can't create user...Sorry @Henni it will have to wait until I sort this out!

**Comment by predus2** [comment]
Yesterday I upgrade OC to 9.0.0 stable, problem still exist - no notes in web ....
maybe I´m not correctly turn off mod_security, I don´t know

**Comment by Henni** [comment]
@ppmt contact me at hendrik@leppelsack.de

**Comment by Henni** [comment]
This issue occurs because of a "misconfigured" mod_security config.
Core introduced the no referrer policy in https://github.com/owncloud/core/commit/436c149fbbca2c26d906dfb871bdafc8c7a2ab34

**Comment by Paviluf** [comment]
Thanks for the fix and for having found the mod_security problem !
