### ISSUE TITLE
Bug with pasting from clipboard

### ISSUE THREAD

**Issue by Loki3000** [owncloud/notes#206]
Steps:

1. Click "new note" button. Creates new empty note:
`POST https://mydomain/index.php/apps/notes/notes`
`GET https://mydomain/index.php/apps/notes/notes/7317`

2. Press Ctrl+v for putting text from clipboard. Text appears in textbox (but there is no PUT request)

3. Click at another note. New GET request in console:
`GET https://mydomain/index.php/apps/notes/notes/513`

4. Click again at last created note:
`GET https://mydomain/index.php/apps/notes/notes/7317`

Expected result:
Saved text from point 2

Actual result:
Empty note. All data is lost.

**Comment by KeiOtori** [comment]
Same problem - copy-paste doesn't works as expected. If you paste something to the note, and then open other note without typing anything new to the pasted data - you lost your note.

**Comment by Henni** [comment]
Which version of the app do you have?
This should have been fixed in https://github.com/owncloud/notes/pull/193

**Comment by Loki3000** [comment]
It was 2.0.0.
In 2.0.1 bug was fixed.
