### ISSUE TITLE
Not working with OC 9

### ISSUE THREAD

**Issue by dynobo** [owncloud/notes#209]
- Old Notes are not shown
- New Notes can't be added
- UI shows strange note (see attachment)

OC Error Log doesn't show anything related.

![notes](https://cloud.githubusercontent.com/assets/11071876/13723133/9c0c412c-e85b-11e5-9396-d7e58658313e.png)

**Comment by tchncs** [comment]
I also upgraded to OC9 and all Notes are still there.

**Comment by dynobo** [comment]
I found this in browser console:

> Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
> Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src https://mydomain.de 'unsafe-eval'"). notes

Might this has something to with it? Any idea, how to get rid of this?

**Comment by handswork** [comment]
I have this one too and this one #210 that I reported

**Comment by LukasReschke** [comment]
Patch is at https://github.com/owncloud/notes/pull/211. Please test.

**Comment by dynobo** [comment]
Yes, seems to be working! :-)
Thanks!

**Comment by josh4trunks** [comment]
Anyone know when 2.0.1 will be available for upgrade through the repo?
