### ISSUE TITLE
404 error when installing

### ISSUE THREAD

**Issue by ldonis** [owncloud/notes#212]
If you try to install using owncloud apps you can see the error
Client error response [url] https://apps.owncloud.com/CONTENT/content-files/174554-notes-2.0.1.zip [status code] 404 [reason phrase] Not Found

When you try to download manually:
https://apps.owncloud.com/content/show.php/Notes?content=174554
you can see the same 404 error

**Comment by Paviluf** [comment]
I tried to install it too and I have the same error :(

**Comment by Henni** [comment]
should be fixed. Thanks for reporting.

**Comment by Paviluf** [comment]
It's fixed. Thanks !
