### ISSUE TITLE
Can't find OwnCloud Notes in 8.2.3

### ISSUE THREAD

**Issue by n00b12345** [owncloud/notes#216]
I just updated OC from 8.2 to 8.2.3 and can't find OwnCloud Notes. Has the app been removed from this particular version?

**Comment by slashrsm** [comment]
Updates usually disabled 3rd party apps. I re-enabled and now all my notes are gone. I can still find the files in "Notes" folder.

**Comment by slashrsm** [comment]
Investigating this further I discovered that I get 404 on the two routes that return list of notes (/apps/notes/notes) and content of the current note (/apps/notes/notes/[note ID]). This happened after upgrade to 8.2.3. It was working without any problems with 8.2.2.

**Comment by Henni** [comment]
@n00b12345 can't reproduce your issue

@slashrsm your issue was fixed by #217

**Comment by slashrsm** [comment]
@Henni Just figured that out by myself too. Thanks!
