### ISSUE TITLE
Can't create new notes and show existing notes from the browser

### ISSUE THREAD

**Issue by predus2** [owncloud/notes#218]
Hi I use android app correctly, show/delete/create notes, but in browser can´t show existing or create new notes, page is simply blank like there any notes. In dir /Notes are *.txt files with notes and correctly created/deleted/changed by android apps, corectly snyc by sync client to pc.

I tried  Fix REST base url #217 (var baseUrl = OC.generateUrl('/apps/notes');), but no chage ...
can you help me?

**Comment by Henni** [comment]
Please add your comment to #205 and mention whether you have mod_security installed.
