### ISSUE TITLE
Empty Notes view after upgrade to Owncloud 9.0.1 // Notes 2.0.1

### ISSUE THREAD

**Issue by guddl** [owncloud/notes#222]
**Steps to reproduce**
1 .I  upgraded from owncloud 8.2.3 over 9.0.0 to 9.0.1
2. Upgraded Notes app to version 2.0.1
3. Open Notes App

**Expected behaviour**
The existing notes should show up in the main view.

**Actual behaviour**
No notes are displayed. Only the "+" sign appears. 
The notes are still there in the Files app

**Server configuration**
Operating system: Ubuntu 12.04
Web server: Apache
Database: Mysql
PHP version: 5.5.9 
ownCloud version: 9.0.1
Updated from an older ownCloud or fresh install: 8.2.3 oder 9.0.0 to 9.0.1

**Comment by iamnumbersix** [comment]
Confirmed

**Server configuration**
Operating system: Debian 8.4
Web server: Apache
Database: Mysql
PHP version: PHP 5.6.19
ownCloud version: 9.0.1
Updated from an older ownCloud with a fresh install: 8.2.2 to 9.0.1

**Comment by Henni** [comment]
fixed by #217 
will be released soon.
