### ISSUE TITLE
ownCloud notes doesn't appear in the apps section

### ISSUE THREAD

**Issue by Bugsbane** [owncloud/notes#225]
Hey there,
I love ownCluod notes, it's clean interface and ability to edit notes created with my text editor.

I recently changed from running a server based on arkOS (Arch) to Yunohost (Debian) and moved to a fresh ownCloud 9.0.1 installation in the process and was surprised to not see ownCloud notes anywhere in ownClouds apps/not enabled section. At first I thought it must be a dependency issue, possibly because Yunohost runs on Nginx, not Apache. When I install the git development version though, it works flawlessly.

I'd really like to be able to install / upgrade ownCloud notes the same way as all my other ownCloud apps though, so I'm asking if it's possible to get ownCloud notes listed in the ownCloud apps area, like all the other apps?

**Comment by Henni** [comment]
I can't reproduce this, maybe someone else can take a look.

**Comment by jluttine** [comment]
I can see OwnNote, but that's a different app. I can't find OwnCloud Notes.

**Comment by Bugsbane** [comment]
I have it now, but I ended up having to manually install it before it would show in the apps area.

**Comment by Croydon** [comment]
Please add it.

**Comment by stefan-niedermann** [comment]
have you enabled experimental apps i  the settings?

**Comment by Bugsbane** [comment]
I don't think I did. I'd chalk this up to user error (at least in my case)
