### ISSUE TITLE
nginx server support planned?

### ISSUE THREAD

**Issue by johnnydvc** [owncloud/notes#228]
Any plans for supporting nginx in the near future?

**Comment by tchncs** [comment]
i dont get it. im already running nginx with oc notes o.O

**Comment by johnnydvc** [comment]
Well, the requirements lists Apache webserver support.
Plus I'm having problems adding/editing notes and syncing with the ownCloud Notes android app.
So I figured that it has to be the server.
Now I remember I used to be running the notes app before the 9.0 upgrade without any problems on nginx.
What's your mobile notes app?

**Comment by tchncs** [comment]
I am using [owncloud-notes by stefan niedermann](https://github.com/stefan-niedermann/OwnCloud-Notes)

**Comment by johnnydvc** [comment]
No changes. I have tried the suggestions from the #219 issue. But moving the files didn't do the trick. Still the only thing the notes app shows is {{note.title|noteTitle}}. Still cannot add or edit any entries.
Any clues?

**Comment by kernins** [comment]
The most likely cause here are wrong urls frontend tries to send requests to. In my OC 9.0.2 / Notes 2.0.1 setup it uses urls like `/apps/notes/notes`, however OC in general uses `/someEntryPoint.php/some/route` schema. And indeed my nginx wasn't configured to route such requests to php.

Simple tmp fix for users would be to add
```
location /apps/notes/
         {
            try_files $uri /index.php$uri;
         }
```

**Comment by johnnydvc** [comment]
Issue closed.
I fixed the problem by replacing the notes app with the latest git version. 
Thanks

**Comment by pierreozoux** [comment]
Thanks @kernins I had to use your trick.

Indeed nginx support would be a nice to have!

**Comment by Henni** [comment]
Nginx support isn't planned for now.

**Comment by pierreozoux** [comment]
:+1:
