### ISSUE TITLE
move to nextcloud?

### ISSUE THREAD

**Issue by stefan-niedermann** [owncloud/notes#235]
Hey guys,

i don't want to anger somebody, this is just a question: Will the notes-app move on to nextcloud or will it stay with owncloud? i think it is compatible with both at the moment, but how long...?

Regards

**Comment by Henni** [comment]
Let's keep it where is is for now. We can still decide when the first breaking changes occur.

**Comment by stefan-niedermann** [comment]
I saw this repository lately: https://github.com/nextcloud/notes
So did you move? I am just confused, i expected a hint in the README.md that this project is now hosted in the nextcloud organisation? or is it a fork and developed indipendently?

**Comment by Henni** [comment]
I would consider it moved as I'm more or less the only maintainer at the moment and I'll continue development over at nextcloud.
And yes, we should hint at this in the README
