### ISSUE TITLE
Unable to add notes

### ISSUE THREAD

**Issue by sonst-was** [owncloud/notes#238]
So I recently updated to owncloud 9.0.3 on my shared hoster and found the Notes app.
So I just activated it  to give it a try but I seem to be unable to add any Notes.

I first click the small + and then "Add note" (or how its called in english) and then nothing happens.

Tried Chromium and Edge, both dont work.

In case you need any further information please ask.

**Comment by phedlund** [comment]
What does your ownCloud and/or web server log say?

**Comment by zuglufttier** [comment]
The same here: Local installation of owncloud on debian, everything is up to date. Nothing happening in the logs of owncloud or the web server.

**Comment by elutz** [comment]
The same here but with ownCloud 8.2.7 yet,
In the js console of Chromium I get this:
`angular.js?v=d1b33ad…:10722 GET https://<mydomain>/owncloud/apps/notes/notes 404 (Not Found)`

Firefox says this:
`22:03:37.285 Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src https://<mydomain> 'unsafe-eval'").1 notes` 
It's a German error message, could mean something like this: The settings of the page blocked the loading of resource to 'self' (maybe bad localization in FF or bad translation by me)

**Comment by djm193** [comment]
Same Problem here. Cannot add any Notes in the webinterface. I have bought die iOS App of Peter Hedlund (CloudNotes). Here I can add and sync notes. The notes made in iOS are also stored in the Notes folder in Owcloud. However, no notes can be made within the webinterface.
I am running on ubuntu 16.04 with OC9.1.

**Comment by zuglufttier** [comment]
Using the android app is working, too. Should be the web interface...

**Comment by Henni** [comment]
I can't reproduce this. Please give some more information including:
* do you have `htaccess.RewriteBase` set inside your config.php
* client/server logs
* maybe even fill out the issue template ;)

I'd also appreciate if someone who is experiencing this issue could create a test account for me to reproduce the problem.

**Comment by djm193** [comment]
first:
here are the logs of OC Server I took from the webinterface:


Error	notes	OCA\Notes\Db\Note Object ( [modified] => 1470042989 [title] => Neue Notiz [content] => [id] => 38728 [_updatedFields:OCP\AppFramework\Db\Entity:private] => Array ( ) [_fieldTypes:OCP\AppFramework\Db\Entity:private] => Array ( [id] => integer [modified] => integer ) )	2016-08-01T09:16:29+00:00

Error	notes	OCA\Notes\Db\Note Object ( [modified] => 1470042674 [title] => Test [content] => Test [id] => 38724 [_updatedFields:OCP\AppFramework\Db\Entity:private] => Array ( ) [_fieldTypes:OCP\AppFramework\Db\Entity:private] => Array ( [id] => integer [modified] => integer ) )	2016-08-01T09:11:14+00:00

Error	notes	OCA\Notes\Db\Note Object ( [modified] => 1470042670 [title] => Neue Notiz [content] => [id] => 38724 [_updatedFields:OCP\AppFramework\Db\Entity:private] => Array ( ) [_fieldTypes:OCP\AppFramework\Db\Entity:private] => Array ( [id] => integer [modified] => integer ) )

Error	notes	OCA\Notes\Db\Note Object ( [modified] => 1470043090 [title] => Neue Notiz [content] => [id] => 38732 [_updatedFields:OCP\AppFramework\Db\Entity:private] => Array ( ) [_fieldTypes:OCP\AppFramework\Db\Entity:private] => Array ( [id] => integer [modified] => integer ) )

The "TEST" note was created with the iOS app, however OC became the error mentioned above. The "TEST" note was stored correctly inside the "Notes" folder which was created automatically after activating "Notes" in owncloud webinterface.

**Comment by Henni** [comment]
Another important info I need:
Did you use the latest git or the release from apps.owncloud.com?
I just pushed an old fix from this repository to the App Store, which might fix this issue.

**Comment by djm193** [comment]
I have tried the version from apps.owncloud.com

Have now tried to deactivate and then activate again - no success.. same problem. Besides this if I try to update to version 2.0.2 I get this error:
Client error response [url] https://github.com/owncloud/notes/releases/download/v2.0.2/notes-2.0.2.tar.gz [status code] 404 [reason phrase] Not Found

**Comment by Henni** [comment]
I fixed the app store download

**Comment by djm193** [comment]
seems as it works right now :-) thank you a lot!

**Comment by zuglufttier** [comment]
Thanks! It's working for me, too. Updating the app solved the problem.
