### ISSUE TITLE
Unable to install/activate Notes

### ISSUE THREAD

**Issue by elutz** [owncloud/notes#239]
Tried to install the Notes app via the Owncloud app store. Install means in this case: Activate.
After doing that I got this error message: 
_Der Ordner für die App ist bereits vorhanden._ (in German)
In English it means something like: _The folder of this app already exists._
In fact there **was** a folder called 'Notes', but before activating the app I renamed it.

**Comment by RealRancor** [comment]
@elutz 

> Der Ordner für die App ist bereits vorhanden. (in German)

Try to delete /path/to/owncloud/apps/notes. Then open your oC installation and enable the app again from the "tools" category and not from the "not enabled" category.

**Comment by elutz** [comment]
Thanks.
Enabling the app from the 'tools' (or so it it is called in my ownCloud installation: 'productivity') I already did before with no avail. 
But deleting of the mentioned folder helped.

Thanks again a lot
Regards 
Lutz
