### ISSUE TITLE
Invalid filename when saving note 

### ISSUE THREAD

**Issue by avalx** [owncloud/notes#246]
I'm using QOwnNotes on my Windows system and Notes app on my Android phone. I found a problem with editing and saving notes from my phone after they were creaded/edited on my computer. It looks like there is a problem how Windows and Android interpret CR/LF (\r\n) in the text. More details with log: [https://github.com/stefan-niedermann/OwnCloud-Notes/issues/140](url)

Could you please take a look into this.

**Comment by Henni** [comment]
I'm not sure yet, whether this is a client or server-side issue. I'll probably investigate next week.

**Comment by avalx** [comment]
I would just like to report that this is still a problem. The only thing that was fixed was that particular issue for QOwnNotes (#408 - changing modified dates without editing). I'm sorry for confusion :(.
