### ISSUE TITLE
Support markdown

### ISSUE THREAD

**Issue by awkwardtechdude** [owncloud/notes#250]
Could you add support for markdown, or at least let me upload markdown files to the Notes folder anyways?

**Comment by tchncs** [comment]
As you can see in the readme, it supports Markdown already.
Not very beauty since it shows it inline but hey... .
And there is a neat [android app](https://github.com/stefan-niedermann/OwnCloud-Notes) for this.

**Comment by Henni** [comment]
Both .txt and .md work fine.

**Comment by tchncs** [comment]
That .md also works is good to know :)
