### ISSUE TITLE
Can't connect to my server.

### ISSUE THREAD

**Issue by aizikil** [owncloud/notes#251]
Hi, so as I mentioned above, I can't connect to my server. I made a self signed certificate and I don't use domain name, so my server address string is "https//195.144.*.*:8006" (note, that port isn't standard). Certificate is imported to my mobile phone and when android app tries to connect to a server the button just hangs with "connecting" message.

**Comment by Henni** [comment]
This is probably an issue with the android app.
Please open an issue in its issue tracker.
