### ISSUE TITLE
Notes with Markup in Android

### ISSUE THREAD

**Issue by Offerel** [owncloud/notes#252]
I have some Textnotes created in the Notes App on NextCloud. After syncing this Notes to the Android App, the Text in this notes seems to interpret Markup Language. For Instance there is a note, containing HexColor Codes. If i open this Note in the Android App, the HexColor Code is in bold Text without the # Sign.

**Comment by Henni** [comment]
Which Android app are you using?

**Comment by Offerel** [comment]
Its the package it.niedemann.owncloud.notes from F-Droid Store.

**Comment by stefan-niedermann** [comment]
Jup. That's mine. Will be fixed in 0.10.0 i guess.
Sorry, you'll have to wait some weeks until it is released.
If it happens with 0.10.0 feel free to open a new issue in https://github.com/stefan-niedermann/Owncloud-Notes/issues

cheers
