### ISSUE TITLE
notes app needs updating for owncloud 10

### ISSUE THREAD

**Issue by lemmy04** [owncloud/notes#259]
...subject says it all i think

**Comment by lemmy04** [comment]
...not even a reaction here?

I've installed a git snapshot of this a week ago or so, works fine but of course gives me code integrity warnings.

**Comment by Henni** [comment]
Both of the maintainers (including me) moved to working on nextcloud and the nextcloud [notes app](https://github.com/nextcloud/notes).

**Comment by DeepDiver1975** [comment]
https://marketplace.owncloud.com/apps/notes
