### ISSUE TITLE
Import notes from ownnotes?

### ISSUE THREAD

**Issue by amca01** [owncloud/notes#260]
I'd like to use "notes" as I can use the Android app MyOwnNotes to keep on top of things when I'm on the road.  But all my notes are currently in the "ownNotes" app.   Is there an easy way to transfer them across?  Or to point "notes" to the folder on my server currently used by "ownNotes"?

Thank you!

**Comment by stefan-niedermann** [comment]
ownNotes uses databse only storing as far as i know, not filebased storing. in this case you could use phpmyadmin to export your notes and save them as txt files

**Comment by cdamken** [comment]
> ownNotes uses databse only storing as far as i know,

you can select that the notes from ownNotes are stored in Storage too, a "Notes" folder will be created.

You have to convert the files from HTML to plain text.

```
#! /bin/bash
for files in *; do
  Filename=${files%%.*}
  echo "$Filename" > [Path where you want to store the new notes]/"$Filename".txt
  lynx --dump -nomargins ./"$files" >>  [Path where you want to store the new notes]/"$Filename".txt
done

```

What I still don't know how to automatize is to have it directly in the Notes app
