### ISSUE TITLE
Notes not supported under ownCloud 10.0.2

### ISSUE THREAD

**Issue by CliffMitchell** [owncloud/notes#261]
I recently upgraded ownCloud to 10.0.2 and get this error when trying to install Notes:

This app cannot be installed because the following dependencies are not fulfilled: ownCloud 9.2 or lower is required.

Will you be releasing a new version of Notes that is supported under 10.0.2 please?

**Comment by lemmy04** [comment]
+1, repeatedly.

That being said: I have installed a git snapshot of the app, which works fine but now i get code integrity warnings because it's of course not signed.
PLEASE release.

**Comment by 3dluvr** [comment]
+1

**Comment by ljephson** [comment]
+1, I've been waiting for an update for a while.

**Comment by DirkPersky** [comment]
+1

**Comment by DeepDiver1975** [comment]
https://marketplace.owncloud.com/apps/notes
