### ISSUE TITLE
Sending unicode through API calls doesn't work

### ISSUE THREAD

**Issue by Dreamsorcerer** [owncloud/notes#29]
If I use a unicode character in a parameter, it doesn't work correctly.

For example, using the new note call with a '£' somewhere in the content, causes it to create a blank new note and ignores the content given.

I've tried using Javascript's escape() function, to see if that helps, but then notes treats it literally, and my notes looks like this:
  Loans%0ADroller%0ALucas%3A%20%A330.54%0AMichael%3A%20Controller%0ABTC%3A%20%28-10%29%20Lucas%2050%25

I am able to receive unicode characters without any problems if I create them in the web interface and then get the notes through the API. It seems I'm just unable to send them successfully.

**Comment by Raydiation** [comment]
Closing because this issue is not reproducable and inactive
