### ISSUE TITLE
Blank page for the note app

### ISSUE THREAD

**Issue by jncolin** [owncloud/notes#291]
Hi,
I'm running  ownCloud 10.0.10 (stable)  php 7.2. I have cloned the github repo into apps/notes and activated it. So I can now see it when I click on the top right menu button. I get to a blank page (except for the top menu)

When I open the developer console (on Firefox 64.0), I see the following. 
Can someone help me? 
![screenshot from 2019-01-29 10-51-14](https://user-images.githubusercontent.com/3629802/51899813-17175000-23b4-11e9-82fc-a2956abae2c4.png)

```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). notes:1:1
JQMIGRATE: Migrate is installed, version 1.4.0 jquery-migrate.min.js:2:542
Deprecation warning: tipsy is deprecated. Use tooltip instead. js.js:2296:2
Error: [$injector:modulerr] Failed to instantiate module Notes due to:
[$injector:nomod] Module 'Notes' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.14/$injector/nomod?p0=Notes
minErr/<@https://leterrier.elfelibre.be/cloud/apps/notes/js/vendor/angular/angular.js?v=93a8e571ce9deceac907376eceed952f:68:12
module/<@https://leterrier.elfelibre.be/cloud/apps/notes/js/vendor/angular/angular.js?v=93a8e571ce9deceac907376eceed952f:2022:17
ensure@https://leterrier.elfelibre.be/cloud/apps/notes/js/vendor/angular/angular.js?v=93a8e571ce9deceac907376eceed952f:1946:38
```

**Comment by paurakhsharma** [comment]
@jncolin Did you try making `make` inside `apps/notes`

**Comment by paurakhsharma** [comment]
So, now what you can do is download notes app tarball from https://marketplace.owncloud.com/apps/notes and extract it inside `apps/`. 
Let me know if this method doesn't work.
Thanks

**Comment by jncolin** [comment]
Excellent, thanks a lot! It works
