### ISSUE TITLE
Not able to activate notes on owncloud 10.1

### ISSUE THREAD

**Issue by jreus** [owncloud/notes#307]
Hello, I run Owncloud on a shared hosting server. And just installed a fresh version using Softaculous, a php software package manager that is run from a Cpanel backend provided by my hosting service.

My owncloud version is 10.1, but when I upload the Notes codebase into the apps directory I get a message "This app cannot be installed because the following dependencies are not fulfilled:

    ownCloud 10.2 or higher is required"

The README states the minimum version of owncloud is 8.1 ... what gives?

best,

Jon
<img width="304" alt="Screen Shot 2019-04-12 at 11 43 43" src="https://user-images.githubusercontent.com/1451059/56028422-59e09700-5d18-11e9-8742-b27cb83177a4.png">

**Comment by alfredbuehler** [comment]
> The README states the minimum version of owncloud is 8.1

This refers to the officially published version (marketplace).

**Comment by DeepDiver1975** [comment]
notes 2.0.5 was just released which is compatible with owncloud 10.2+ - just FYI.
2.0.4 was working find for 8.2-10.1 - no idea why you did get that error.

I'm anyway closing this for the time being. THX
