### ISSUE TITLE
Notes app not available in ownCloud 10.2

### ISSUE THREAD

**Issue by alariej** [owncloud/notes#312]
Hi, I just installed a fresh ownCloud server (10.2.0 Stable) and the Notes app is not available in the Market. The app seems to still be monitored at https://marketplace.owncloud.com/apps/notes, but it states that the latest version 2.0.4 is tested up to ownCloud version 10.1.

Is there any plan to make it available in 10.2?

Thanks and regards.

**Comment by DeepDiver1975** [comment]
Just published 2.0.5 which supports 10.2+ - have fun!

**Comment by alfredbuehler** [comment]
> Just published 2.0.5 which supports 10.2+ - have fun!

@DeepDiver1975: Nice, but IMHO it isn't  a very nice move, setting min-version="10.2", unless really required. Please don't punish the instant-upgraders!

**Comment by DeepDiver1975** [comment]
>  unless really required.

Due to the move to semver with owncloud 10.1 this was a neccessary change - see https://owncloud.org/news/switching-owncloud-to-semantic-versioning-semver/

For anybody up to 10.1 2.0.4 can be used - anybody on 10.2+ can use 2.0.5.

Am I missing anything? THX

**Comment by alfredbuehler** [comment]
I don't see that requirement, sorry. But let's stop here, I'm afraid it's becoming OT.
