### ISSUE TITLE
App only visible for admins

### ISSUE THREAD

**Issue by thefeiter** [owncloud/notes#314]
The Notes Icon in the menue in the upper left corner does only show up for admin users. I don not have the option "activated only for certain groups" enabled and have a quite fresh install of ownCloud 10.2.0 and just installed the Notes App.
For Admins it works fine!

**Comment by thefeiter** [comment]
oh, but when I manually open the link to the Notes page it works for non admins too

**Comment by alfredbuehler** [comment]
Confirmed.

You could stay at 2.0.4, but unfortunately this requires some manual adjustments.

**Comment by thefeiter** [comment]
ok, for now I will be using your plugin for Firefox and the manual link.

**Comment by as149** [comment]
Hi,
I also have the same problem too.
In Version 2.0.5 there ist still no Icon in menue.
Is it already solved?

**Comment by as149** [comment]
:thumbsup: it works.
Thank you.
