### ISSUE TITLE
Notes Release 2.1.0

### ISSUE THREAD

**Issue by phil-davis** [owncloud/notes#406]
There have been lots of JavaScript dependency updates merged recently. For example:
#398 
#399 
#400 
#402 
#403 

And we dropped support for PHP 7.2 in #404 

I just manually tried the Notes webUI and that seems to work with current core master.

We could release a new version of notes when core 10.9.0 is coming out, or?

**Comment by jnweiger** [comment]
@DeepDiver1975 do you want to do this release?

**Comment by jnweiger** [comment]
@phil-davis this will be released as part of 2.0.6 now.
I guess a patchlevel bump is sufficient. The new deps don't bring functional changes, (hopefully)
Followup -> #490

**Comment by phil-davis** [comment]
> this will be released as part of 2.0.6 now

Agree. I'm not sure why I mentioned 2.1.0 in the title of this issue.
