### ISSUE TITLE
Always creating notes, endless.

### ISSUE THREAD

**Issue by binarykitchen** [owncloud/notes#441]
![2023-03-07_19-36](https://user-images.githubusercontent.com/177641/223341800-3c708f4e-8b97-4a21-a903-4c5b561a843f.png)

Screenshot says it all. Will collect all the other information now and put them below.

**Comment by binarykitchen** [comment]
Nextcloud

```
Nextcloud Hub II (23.0.10)
````

Server

```
Operating System:	Linux 5.15.0-1031-aws x86_64
CPU:	Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz (1 core)
Memory:	966.00 MB
Server time:	Tue Mar 7 19:39:53 NZDT 2023
```

PHP

```
Version: 8.0.28
Memory Limit: 512 MB
Max Execution Time: 3600
Upload max size: 16 GB
```

DB

```
Type: sqlite3
Version: 3.37.2
Size: 215.2 MB
```

**Comment by phil-davis** [comment]
@binarykitchen this is the repo for the ownCloud notes app.

You seem to be using NextCloud.
