### ISSUE TITLE
Need help with API

### ISSUE THREAD

**Issue by stefan-niedermann** [owncloud/notes#54]
Hi,

i tried to create a new note via API. (OwnCloud 6.0.3, newest Notes-App).
If i submit, a new note is created on server side, but the content is empty, so the title of the created note is only "New Note (n)".

Creating a Note through web interface works very well and fetching all News with my custom Application does also work well.

I recorded the following snippet of my Application with wireshark and i am not able to see any fault.
Authentication is correct, URL is correct. Are you able to see any fault?

![screenshot](https://cloud.githubusercontent.com/assets/4741199/3629049/8a9885c2-0e9b-11e4-9d4b-67b8babc37f7.png)

**Comment by LukasReschke** [comment]
Still required?

**Comment by stefan-niedermann** [comment]
No, thanks.
