### ISSUE TITLE
able to create an "invisible" note

### ISSUE THREAD

**Issue by steppenhahn** [owncloud/notes#63]
hi.
i was able to create a note via [MyOwnNotes](https://github.com/aykit/myownnotes-android)  that is not shown in the notes-app interface but is visible under Files/Notes as " .txt"

how? i created a new note with a single space in the first line, and text in the second line, like this:
[content start]
 
secret note
[content end]

i mean like:
[content start]
_space_
secret note
[content end]

(without the []'s and the text in them)

the note is created as " .txt" and shown under Files/Notes, and is editable and syncable via notes-api but is _not_ shown in the notes list under Notes
if i create another note like this, a " (2).txt" is created - but this note then _is_ displayed in the notes list.

rather interesting :)

reproducible in owncloud versions 7.0.1 & 7.0.2

**Comment by Raydiation** [comment]
Core issue
