### ISSUE TITLE
[enhancement] Notes in imap folder

### ISSUE THREAD

**Issue by nbenm** [owncloud/notes#68]
Hi,

I tried the app and it looks fine.
I use notes in imap folder (Apple, gmail, yahoo... method).
Would it be possible to adapt code to do this.
I'm not php dev at all, but I can provide python code to list notes, search notes containing a string, update a note, store a new note and delete a note in such an imap folder notes.

Regards

**Comment by Popyllol** [comment]
Yes, a notes app which provides access to the IMAP-Notes-folder would be great!
Is anyone working on this issue?

**Comment by Raydiation** [comment]
Nope ;)

This app stores notes in the filesystem. If you want to edit imap notes, use a different app or request it in the mail app
