### ISSUE TITLE
Notes folder name hardcoded

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/notes#7]
Seems from the files/Note in https://github.com/owncloud/notes/blob/master/lib/notes.php that the Notes folder name is hardcoded. cc @caco3

Rather it should probably be a language-dependent variable much like for Pictures and Music. cc @butonic

**Comment by fcturner** [comment]
Sorry to comment on an old issue, but I just wanted others to know how to make the folder language dependant. I do understand the problems it might cause when the folder is renamed or removed, but for all Googlers and DuckDuckGo-ers, here is a solution:

Find and replace the following value in `apps/notes/service/noteservice.php`:
`'/files/Notes'`
by 
`'/files/' . $this->l10n->t('Notes')`

This will search for a folder with the translated name of the app. So for German it searches for the root folder `Notizen`, for Spanish `Notas` and so forth. Really helps me on our family private cloud. Pity to *need* an English named folder in a foreign language.

Besides, it **does** work on the iOS app [CloudNotes](https://itunes.apple.com/us/app/cloudnotes-owncloud-notes/id813973264?mt=8).

**Comment by fcturner** [comment]
This might however change when #69 gets solved :smile:
