### ISSUE TITLE
OC_Filesystem' not found

### ISSUE THREAD

**Issue by th3gr1d** [owncloud/notes#71]
I am currently stuck with getting this error msg running the latest version of ownCloud. In my logs relating to the Notes App it has entries showing the following:-

Class 'OC_Filesystem' not found at /home/xxxxx/public_html/owncloud/apps/notes/templates/notes.php#27

I can enable the app in the admin panel but when I try to open the Notes app it directs me to a blank page.

Many thanks

**Comment by LukasReschke** [comment]
Should be fixed with the master branch of core and this app.
