### ISSUE TITLE
Notes not available on apps.owncloud.com

### ISSUE THREAD

**Issue by phedlund** [owncloud/notes#73]
Users of clients wonder where to get the server app.

**Comment by ericfont** [comment]
please update your readme to change "Activate the Notes app in the apps menu" into directions for cloning the git into a local owncloud server directory.  

I spent way too much time trying to figure out why I couldn't find the notes app in the store and wondering if I had something wrong with my configuration, while the simple truth was that OC app store doesn't list it.

**Comment by rakekniven** [comment]
@ericfont : No need to clone (git) anything to your server.
Just download a zip file from github and place content on your server in preferred way (ftp, scp, browser tool, ...)

**Comment by rakekniven** [comment]
btw. please release version 1.0.0 (which has been tagged) to app store. Thx.

**Comment by rakekniven** [comment]
Any reason not putting it on apps.owncloud.com? Users look there in the first spot, not here.

**Comment by sorglos** [comment]
@rakekniven: The app store is a bunch of garbage. Outdated and unmaintained apps.  :-1:

**Comment by rakekniven** [comment]
@sorglos Not sure if your comment is helpful in anyway.
New ownCloud server versions are grabbing information for installed apps from the store.
Any integrated update option due to "new version available" label in web UI sound good to me.
Like for the news app.

**Comment by Henni** [comment]
I just released the notes app on the app store:
https://apps.owncloud.com/content/show.php?content=174554

Please test it and feel free to rate it.
Screenshots, a detailed description and hopefully the approved state will follow soon.
