### ISSUE TITLE
Enabling app in OC 7.0.4 / PHP 5.6.4

### ISSUE THREAD

**Issue by Bugsbane** [owncloud/notes#76]
Hi there,

I downloaded and extracted the 0.8 release into the app folder of my ownCloud 7.0.4, but when I click "Enable" in the app section, it loads for a moment and then just returns the error:

"No app name specified"

* I'm using:
* ownCloud 7.0.4
* notes 0.8
* PHP 5.6.4
* MariaDB

In the log I see:
> is_file(): open_basedir restriction in effect. File($PATHTOOWNCLOUD/apps/notes-0.8.tar.gz/appinfo/app.php) is not within the allowed path(s): (/srv/http/:/home/:/tmp/:/usr/share/pear/:/usr/share/webapps/) at $PATHTOOWNCLOUD/lib/private/app.php#810 

$PATHTOOWNCLOUD has been substituted for the actual path.

**Comment by kevin-carlson** [comment]
Rename the extracted folder from 'notes-0.8' to 'notes'

**Comment by Bugsbane** [comment]
Thanks. That did it. Thanks for the simple but highly useful app.
