### ISSUE TITLE
Text area has shrinked height

### ISSUE THREAD

**Issue by fossxplorer** [owncloud/notes#77]
It seems commits after 09275738b2bcc05fdac0af5715acdef43dcd94a6 breaks the visible text area.
When you edit text and add content, the top is pushed upwards and invisible.

@jancborchardt

**Comment by sanneterpstra** [comment]
Same here

**Comment by beli3ver** [comment]
Same here
![bildschirmfoto 2015-01-18 um 14 36 01](https://cloud.githubusercontent.com/assets/7816755/5792576/63772bd2-9f1f-11e4-82c0-42a7d91735a4.png)

**Comment by JanMalte** [comment]
@fossxplorer The commit you mentioned hasn't changed any files which seems related to this issue.

**Comment by LukasReschke** [comment]
Can't reproduce please post the steps you did and which browser / OS you're using.

Furthermore try again with all plugins disabled. Third-party plugins such as Adblock do insane stuff to prevent from ads having showing and so often break our stuff. – If it works with ADB disabled complain to them instead.

**Comment by LukasReschke** [comment]
Was able to reproduce – let me try to fix this.

**Comment by MarvAmBass** [comment]
got this in chrome and firefox (latest) under windows, macosx and linux

it has something to do with the height of the textarea element. it's set to 100% - but it seems, that the parent div limits that 100%.

I was able to quick fix it by adding a a 

    style="height:100%"

to

    <div id="app-content-container" class="ng-scope" ng-view="">

it might be broken because of changes in the app-content-container css

**Comment by hermanthe** [comment]
How/where do i have to make the changes to fix the bug

**Comment by MarvAmBass** [comment]
https://github.com/owncloud/notes/blob/master/templates/main.php#L58

just add a 

    style="height:100%"

for a quickfix

**Comment by hermanthe** [comment]
Thanks, works for me

**Comment by jancborchardt** [comment]
Fix at https://github.com/owncloud/notes/pull/83, please review! @MarvAmBass you are also welcome to submit pull requests yourself. :rocket:
