### ISSUE TITLE
[bug] Text area has shrinked height (again)

### ISSUE THREAD

**Issue by nodiscc** [owncloud/notes#84]
Hi @LukasReschke @jancborchardt , I recently installed the notes app by cloning this repo. This is on the `master` branch. #77 doesn't seem to be fixed for me:

![oc-notes-bug](https://cloud.githubusercontent.com/assets/3950390/5959005/a3bb17a4-a7ca-11e4-91d8-d2230885bee3.png)

I highlighted the text area in Firefox's inspector, and it's box model only has a 30px 20px 100px 30px padding. Can you confirm? This is on both Firefox 34 and 35

**Comment by LukasReschke** [comment]
Will take a look once 8 is out…

**Comment by nodiscc** [comment]
Thanks for the quick replay @LukasReschke ; this might be related to https://github.com/owncloud/notes/issues/60

**Comment by jancborchardt** [comment]
I can not reproduce this. While #60 is indeed still an issue, #77 is fixed. Are you sure this isn’t a caching issue? Try force reloading with Ctrl+Shift+R, and also try in other browsers.

**Comment by nodiscc** [comment]
This is a fresh owncloud 7 install on a Debian stable / apache2 server. I've cleared my cache. I can reproduce it on Firefox 35.0 on Win7 and Iceweasel (Firefox) 34.0 on Debian. @jancborchardt What browser are you using? I get no errors on the console

**Comment by jancborchardt** [comment]
Please test in at least one other browser, like Chrome/Chromium. I use both Firefox and Chrome.

**Comment by Raydiation** [comment]
Can not reproduce, neither in firefox nor chrome, closing therefore.
