### ISSUE TITLE
Conflict caused by sync with windows desktop client

### ISSUE THREAD

**Issue by Jas2Ma** [owncloud/notes#85]
First of all: Why can't I find Notes in owncloud app store (apps.owncloud.org) anymore?

Concerning the bug: When I change a file in the MyOwnNotes Android app or in the Web-Interface, Windows Client will download the file again and again. Furthermore, I can't change the file in the synced Notes directory, because it won't be uploaded, but a file conflict is appearing.

Can you help me? Is this cause by a bug in the Notes app?
I don't get errors in the owncloud log related to this issue.

It does not happen in other synced directories.

It is not correlated to timestamps of the files as far as I can see (they seem to be ok).

**Comment by Raydiation** [comment]
Not a notes app bug, this is related to the sync client, open there
