### ISSUE TITLE
Add support for sub directories

### ISSUE THREAD

**Issue by LudovicRousseau** [owncloud/notes#87]
I like to store my notes in different folders for different categories.

It is possible to create sub-folders in the Notes directory on OwnCloud Files application. But files present in the sub-folder are NOT visible to the Notes web application and also to the Android application https://github.com/aykit/myownnotes-android.

Is it a by design choice to avoid sub directories?
If not, can it be added?

See also https://github.com/aykit/myownnotes-android/issues/102

**Comment by ramschmaerchen** [comment]
Just a note: I myself like the minimal approach of notes. For me, subfolders would be over engineering.

**Comment by LukasReschke** [comment]
Yes – I'd avoid that as well. For now not a priority. Sorry.

**Comment by sorglos** [comment]
It's bad to hear. I have my notes structured in sub-folders in the Notes folder. This feature is discussed in #2 since two years. ;-)
