### ISSUE TITLE
Add support of MarkDown syntax ?

### ISSUE THREAD

**Issue by LudovicRousseau** [owncloud/notes#88]
It would be nice to be able to render the notes text as markdown.

On the server side it is possible to use owncloud-markdown https://github.com/icewind1991/owncloud-markdown to edit text as MarkDown.
The problem is the server Notes application (and the Android Notes application) can only use ``.txt`` files (and not ``.md`` files).

I see in https://github.com/owncloud/notes/tree/master/js/vendor/markdown that the Notes application already knows about markdown. But this has been removed in version 0.9 of Notes:
```
owncloud-notes (0.9)
* Security: Remove markdown support because of [XSS in markdown-js library](https://github.com/evilstreak/markdown-js/pull/52)
```

I propose you to: allow the Notes applications to use the ``.md`` extension. The files are still pure text files. So I will be able to use owncloud-markdown to edit my notes on the server.

Add the ability to preview the markdown in Notes directly would be great but not really needed if I can edit them using owncloud-markdown.

See also the bug I opened at myownnotes-android
 https://github.com/aykit/myownnotes-android/issues/103

**Comment by LukasReschke** [comment]
Agreed – will add it in a future release.

**Comment by LukasReschke** [comment]
Dupe of https://github.com/owncloud/notes/issues/81
