### ISSUE TITLE
Owncloud 8.0 / Notes app 0.5: "delete" button is missing.

### ISSUE THREAD

**Issue by lemmy04** [owncloud/notes#91]
After updating my owncloud to 8.0 the "delete" button is missing from the notes list.
I still get a working "delete" link by hovering the mouse over the right spot, but there's no visual indication of that area being a link.

Clearing cache, trying a different browser didn't make a difference.

Nothing stands out in the logs either.

**Comment by LukasReschke** [comment]
Can you test with the version from https://github.com/owncloud/notes/archive/master.zip?

/me still needs to figure out how that whole Appstore thing works without breaking all older versions…

**Comment by lemmy04** [comment]
that works now, and it also fixed #91 as well...
