### ISSUE TITLE
Owncloud 8.0 / Notes app 0.5: cannot save new notes

### ISSUE THREAD

**Issue by lemmy04** [owncloud/notes#92]
After update to OC 8.0 I cannot create new notes.

I click on "new note", enter text, the title of the note changed to whatever my first line of text is, but after a second or two it changes back to "New note", and if I select a different note the new content is lost.
Same goes for editing existing notes.

**Comment by LukasReschke** [comment]
Same as https://github.com/owncloud/notes/issues/91#issuecomment-74865972 - please test with that version before creating more issues ;-)

**Comment by lemmy04** [comment]
that updated version fixes both #91 and #92
