### ISSUE TITLE
In API send hashed password instead of password

### ISSUE THREAD

**Issue by raginggoblin** [owncloud/notes#93]
The API requires to send the original password. This requires every client application to store the password locally. Of course I use encryption, but still this is insecure. A better way would be to require a hashed password with a known algorithm (e.g. SHA-256) so the clients only have to store the hash. This is more secure.

**Comment by LukasReschke** [comment]
This can be mitigated by relying on clients that store their secrets properly.

Having per-context tokens is out-of-scope for the notes app and might be added once core supports this.
