### ISSUE TITLE
yesterday update oc to 8.0 today notes ask for update 

### ISSUE THREAD

**Issue by 1xhabit** [owncloud/notes#94]
hello, i'm currently running owncloud 8.0 the update have need hours. so i'was clone the notes repository 
in apps directory and seconds later owncloud means the want update to owncloud version 8.0

so, if delete the notes app. everything is ok again. 

i'dont know what is the problem????

**Comment by LukasReschke** [comment]
Sorry, I don't understand what the problem is. Can you please fill out the issue template? See https://github.com/owncloud/core/blob/master/CONTRIBUTING.md – THX.

**Comment by 1xhabit** [comment]
Hello Lukas, 

sry it was my problem. wrong install! now its work. with OC 8.0.2

i'use the OSX and IOS clients! OS X Yosemite and the newest iOS.
On OS X sometimes i get a lot new notes with no content ... i'dont know why. maybe the sync ist there sometimes not correct and the client create random empty notes. 

ok, thx. for your attention. and please put the notes osx app in the App Store i'will pay this app. 

bye xhabit
