### ISSUE TITLE
Installed on OC8, it does'nt work correct

### ISSUE THREAD

**Issue by Kenarso** [owncloud/notes#98]
I have the problem, that if wanna use the app I get only a note list, and a area of text. thats all.
I can't use any other function.
Anybody an Idea?
I use Firefox on ElementaryOS (Ubuntu based) an OC 8.0.2
![bildschirmfoto vom 2015-03-15 11 29 16](https://cloud.githubusercontent.com/assets/9461091/6655632/a34ea146-cb06-11e4-93d6-b4631c4717fa.png)

**Comment by Dreamsorcerer** [comment]
I'm seeing the same issue. Upon upgrading to OC 8, all my old notes are still present, but if I create a new note or modify one it quickly resets to a blank note with no content. This happens both in the web interface and using the API.

**Comment by Raydiation** [comment]
Needs more information, especially javascript console output

**Comment by Dreamsorcerer** [comment]
Sorry, figured this out a few days ago. The version available when browsing in OwnCloud is out of date. Manually installing the current release fixes the issue.
